backend:
  name: git-gateway
  branch: jigsaw

media_folder: "source/assets/images"
public_folder: "assets/images"

collections:
  - label: "Pages"
    name: "pages"
    delete: false
    files:
      - label: "About Page"
        name: "about"
        file: "source/about.md"
        fields:
          - {label: "Extends", name: "extends", widget: "hidden", default: "_layouts.inner"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "text"}
          - {label: "Section", name: "section", widget: "hidden", defaut: "body"}
          - {label: "Body", name: "body", widget: "markdown", buttons: ['bold', 'italic', 'code', 'link', 'heading-two', 'quote', 'code-block', 'bulleted-list', 'numbered-list', 'image']}
    